from typing import List
from typing import Literal
from typing import TypedDict
from typing import Union

from typing_extensions import NotRequired

PERIOD_FISCAL_PERIOD = Literal["Y", "Q1", "Q2", "Q3", "Q4" "3QCUM", "H1", "H2"]

# Define allowed values for method
AcceptableMethods = Literal[
    "assertion search",
    "concept name search",
    "concept search",
    "cube search",
    "dimension search",
    "document search",
    "dts id concept label",
    "dts id concept name",
    "dts id concept reference",
    "dts id concept search",
    "dts id network",
    "dts id network search",
    "dts search",
    "entity id",
    "entity id report search",
    "entity report search",
    "entity search",
    "fact id",
    "fact search",
    "fact search oim",
    "label dts id search",
    "label search",
    "network id",
    "network id relationship search",
    "network relationship search",
    "relationship search",
    "relationship tree search",
    "report fact search",
    "report id",
    "report id fact search",
    "report search",
]
"""All fields with type information for the fact endpoint."""


# Fact
FACT_ENDPOINTS = Literal["/fact/search", "/fact/{fact.id}", "/fact/search/oim"]
FACT_FIELDS = List[
    Literal[
        "aspect",
        "concept.balance-type",
        "concept.datatype",
        "concept.id",
        "concept.is-base",
        "concept.is-monetary",
        "concept.local-name",
        "concept.namespace",
        "concept.period-type",
        "dimension-pair",
        "dimension.is-base",
        "dimension.local-name",
        "dimension.namespace",
        "dimensions",
        "dimensions.count",
        "dimensions.id",
        "dts.entry-point",
        "dts.id",
        "dts.target-namespace",
        "entity.cik",
        "entity.code",
        "entity.id",
        "entity.name",
        "entity.scheme",
        "fact.accuracy-index",
        "fact.decimals",
        "fact.has-dimensions",
        "fact.hash",
        "fact.id",
        "fact.inline-display-value",
        "fact.inline-is-hidden",
        "fact.inline-negated",
        "fact.inline-scale",
        "fact.is-extended",
        "fact.numerical-value",
        "fact.ultimus",
        "fact.ultimus-index",
        "fact.value",
        "fact.value-link",
        "fact.xml-id",
        "footnote.id",
        "footnote.lang",
        "footnote.role",
        "footnote.text",
        "member.is-base",
        "member.local-name",
        "member.member-value",
        "member.namespace",
        "member.typed-value",
        "period.calendar-period",
        "period.end",
        "period.fiscal-id",
        "period.fiscal-period",
        "period.fiscal-year",
        "period.id",
        "period.instant",
        "period.start",
        "period.year",
        "report.accession",
        "report.creation-software",
        "report.document-index",
        "report.document-type",
        "report.documentset-num",
        "report.entry-url",
        "report.event-items",
        "report.filing-date",
        "report.form-type",
        "report.hash",
        "report.html-url",
        "report.id",
        "report.is-most-current",
        "report.period-end",
        "report.period-focus",
        "report.restated",
        "report.restated-index",
        "report.sec-url",
        "report.sic-code",
        "report.source-id",
        "report.source-name",
        "report.submission-type",
        "report.type",
        "report.year-focus",
        "unit",
        "unit.denominator",
        "unit.numerator",
        "unit.qname",
        "fact.*",
    ]
]

FACT_PARAMETERS = TypedDict(
    "FactParameters",
    {
        "concept.id": NotRequired[Union[str, List[str]]],
        "concept.is-base": NotRequired[Literal["true", "false"]],
        "concept.is-monetary": NotRequired[Literal["true", "false"]],
        "concept.local-name": NotRequired[Union[str, List[str]]],
        "concept.namespace": NotRequired[Union[str, List[str]]],
        "dimension.is-base": NotRequired[Literal["true", "false"]],
        "dimension.local-name": NotRequired[Union[str, List[str]]],
        "dimension.namespace": NotRequired[Union[str, List[str]]],
        "dimensions.count": NotRequired[Union[str, List[str]]],
        "dimensions.id": NotRequired[Union[str, List[str]]],
        "dts.entry-point": NotRequired[Union[str, List[str]]],
        "dts.id": NotRequired[Union[str, List[str]]],
        "dts.target-namespace": NotRequired[Union[str, List[str]]],
        "entity.cik": NotRequired[Union[str, List[str]]],
        "entity.id": NotRequired[Union[str, List[str]]],
        "fact.has-dimensions": NotRequired[Literal["true", "false"]],
        "fact.hash": NotRequired[Union[str, List[str]]],
        "fact.id": NotRequired[Union[str, List[str]]],
        "fact.is-extended": NotRequired[Literal["true", "false"]],
        "fact.text-search": NotRequired[Union[str, List[str]]],
        "fact.ultimus": NotRequired[Literal["true", "false"]],
        "fact.ultimus-index": NotRequired[Union[str, List[str]]],
        "fact.value": NotRequired[Union[str, List[str]]],
        "fact.value-link": NotRequired[Union[str, List[str]]],
        "member.is-base": NotRequired[Literal["true", "false"]],
        "member.local-name": NotRequired[Union[str, List[str]]],
        "member.typed-value": NotRequired[Union[str, List[str]]],
        "member.member-value": NotRequired[Union[str, List[str]]],
        "member.namespace": NotRequired[Union[str, List[str]]],
        "period.calendar-period": NotRequired[Union[str, List[str]]],
        "period.fiscal-id": NotRequired[Union[str, List[str]]],
        "period.fiscal-period": NotRequired[Union[PERIOD_FISCAL_PERIOD, List[PERIOD_FISCAL_PERIOD]]],
        "period.fiscal-year": NotRequired[Union[str, List[str]]],
        "period.id": NotRequired[Union[str, List[str]]],
        "period.year": NotRequired[Union[str, List[str]]],
        "report.accession": NotRequired[Union[str, List[str]]],
        "report.creation-software": NotRequired[Union[str, List[str]]],
        "report.document-type": NotRequired[Union[str, List[str]]],
        "report.document-index": NotRequired[Union[str, List[str]]],
        "report.entry-url": NotRequired[Union[str, List[str]]],
        "report.id": NotRequired[Union[str, List[str]]],
        "report.restated": NotRequired[Union[str, List[str]]],
        "report.restated-index": NotRequired[Union[str, List[str]]],
        "report.sec-url": NotRequired[Union[str, List[str]]],
        "report.sic-code": NotRequired[Union[str, List[str]]],
        "report.source-id": NotRequired[Union[str, List[str]]],
        "report.source-name": NotRequired[Union[str, List[str]]],
        "unit": NotRequired[Union[str, List[str]]],
    },
    total=False,  # Makes all fields optional
)
FACT_SORT = TypedDict(
    "FactSort", {field: NotRequired[Union[str, List[str]]] for field in ["1", "2", "3"]}, total=False  # Makes all fields optional
)
